### ISSUE TITLE
10.15 EFI问题

### ISSUE THREAD

**Issue by tamplin** [gaofeicm/DiYuHuo-X6-Hackintosh#1]
机型：地狱火X6 
1.开机颜色“护眼”模式
2.UHD 630显存1536MB
3.蓝牙无法关闭、搜索不到设备，手机也发现不了本机 “MacBookPro”

希望大大解决一下

**Comment by gaofeicm** [comment]
无线网卡我已更换为联想BCM94352Z，若不是此网卡，请另寻方法。
显存多少无所谓，驱动了就行
护眼模式并未在我的电脑出现，若你电脑有此问题，可在系统设置里面更正回来
更换kext后切记开机之后重建缓存重启

**Comment by xy815661276** [comment]
安装的时候重启就会疯狂闪屏。作者有办法吗

**Comment by gaofeicm** [comment]
> 安装的时候重启就会疯狂闪屏。作者有办法吗

是安装的时候闪屏还是安装完重启的时候闪屏？

**Comment by xy815661276** [comment]
> > 安装的时候重启就会疯狂闪屏。作者有办法吗
> 
> 是安装的时候闪屏还是安装完重启的时候闪屏？

不管啥时候，重启就会闪，已经解决了，换了缓冲帧。

**Comment by gaofeicm** [comment]
> > > 安装的时候重启就会疯狂闪屏。作者有办法吗
> > 
> > 
> > 是安装的时候闪屏还是安装完重启的时候闪屏？
> 
> 不管啥时候，重启就会闪，已经解决了，换了缓冲帧。

是地狱火X6吗
